name: nearest_beer
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  dio: ^5.3.3
  dartz: ^0.10.1
  data_connection_checker_tv: ^0.3.5-nullsafety
  shared_preferences: ^2.2.1
  go_router: ^11.1.2
  animated_icon_button: ^1.0.2
  simple_animations: ^5.0.2
  geolocator: ^10.1.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
